#ifndef OFLAUNCHER_STAINLESS_OFSGUIACTS_H
#define OFLAUNCHER_STAINLESS_OFSGUIACTS_H

enum GuiActs { // Add an activity name here
	NOT_CLICKED,
	BUT_CLICKED_UPDATE,
	TAB_CLICKED_OPTIONS,
	TAB_CLICKED_MAIN
};

#endif // OFLAUNCHER_STAINLESS_OFSGUIACTS_H