#ifndef OFLAUNCHER_STAINLESS_OFSGUIACTS_H
#define OFLAUNCHER_STAINLESS_OFSGUIACTS_H

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 360

enum GuiActs { // Add an activity name here
	NOT_CLICKED,
	BUT_CLICKED_UPDATE,
	TAB_CLICKED_OPTIONS,
	TAB_CLICKED_MAIN,
	BUT_CLICKED_INSTALL,
	BUT_CLICKED_CANCEL
};

#endif // OFLAUNCHER_STAINLESS_OFSGUIACTS_H